### ISSUE TITLE
AttributeError: 'interpreter' object has no attribute 'myip'

### ISSUE THREAD

**Issue by mytrix-technology** [dylanmeca/labsecurity#4]
> **Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

This is my error after run labsecurity on command terminal

> Traceback (most recent call last):
  File "/usr/local/bin/labsecurity", line 4, in <module>
    __import__('pkg_resources').run_script('labsecurity==1.7', 'labsecurity')
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/labsecurity-1.7-py3.9.egg/EGG-INFO/scripts/labsecurity", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/labsecurity-1.7-py3.9.egg/libsecurity/__init__.py", line 14, in <module>
AttributeError: 'interpreter' object has no attribute 'myip'

can you help me?

Thanks

**Comment by dylanmeca** [comment]
Hello, I already fixed the error I had forgotten to remove a variable, it is that yesterday I was testing if it was possible for the serverlla library to join with labsecurity, currently the labsecurity project is under development.

But I plan to make this project multipurpose.

You can re-clone the repository for bug fix and reinstall the software with ```python3 setup.py install```.
